version: '3.8'

services:
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "8081:80"       # Port externe changé pour éviter les conflits
      - "8443:443"      # Port HTTPS modifié
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - api
      - flask-app

  frontend:
    build: ./api/public
    ports:
      - "3000:80"       # Changé de 80:80 pour éviter le conflit
    volumes:
      - ./api/public:/usr/share/nginx/html  # Montage pour le développement

  api:
    build: ./api
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
    ports:
      - "3001:3000"     # Exposé sur un port différent
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db

  flask-app:
    build: ./flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./flask-app:/app  # Montage pour le développement

volumes:
  mongodb_data: