version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+pymysql://root:rootpassword@db:3306/item_db"  # Use 'db' as host
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Must set root password
      MYSQL_DATABASE: item_db            # Database name
      MYSQL_USER: app_user               # Custom user (optional)
      MYSQL_PASSWORD: userpassword       # Custom user password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql_data:

networks:
  backend: